# Generated by Django 3.1 on 2020-09-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='firebase uid'),
        ),
    ]
