# Generated by Django 3.1 on 2020-09-30 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regularity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=2, verbose_name='notification type')),
                ('week_days', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=13)),
                ('times_a_week', models.SmallIntegerField(blank=True, null=True, verbose_name='times a week')),
                ('time_of_month', models.CharField(blank=True, choices=[('B', 'Beginning'), ('M', 'Middle'), ('E', 'End')], max_length=2, verbose_name='time of month')),
                ('reminder', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Regularities',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='KitPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('priority', models.CharField(choices=[('T', 'Top'), ('M', 'Middle'), ('L', 'Low')], max_length=2, verbose_name='priority')),
                ('contact', models.CharField(max_length=256, verbose_name='contact')),
                ('regularity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kit_people.regularity', verbose_name='regularity')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kit_people.role', verbose_name='role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('interaction_way', models.CharField(max_length=128, verbose_name='interaction way')),
                ('kit_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kit_people.kitperson', verbose_name='kit person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
