# Generated by Django 3.1 on 2020-09-30 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kit_people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitperson',
            name='regularity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kit_people.regularity', verbose_name='regularity'),
        ),
    ]
