# Generated by Django 3.1 on 2020-10-05 12:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kit_people', '0002_auto_20200930_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitperson',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='regularity',
            name='reminder',
            field=models.TimeField(verbose_name='reminder time'),
        ),
        migrations.AlterField(
            model_name='regularity',
            name='times_a_week',
            field=models.SmallIntegerField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'SIX'), ('7', 'Once every 2 weeks')], null=True, verbose_name='times a week'),
        ),
        migrations.AlterField(
            model_name='regularity',
            name='week_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=13, verbose_name='week days'),
        ),
    ]
