# Generated by Django 3.1 on 2020-10-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_people', '0003_auto_20201005_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularity',
            name='time_of_month',
            field=models.CharField(blank=True, choices=[('BE', 'Beginning'), ('MI', 'Middle'), ('EN', 'End'), ('AN', 'Any time')], max_length=2, verbose_name='time of month'),
        ),
    ]
