# Generated by Django 3.1.2 on 2020-10-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_people', '0005_auto_20201010_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularity',
            name='times_a_week',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Once every 2 weeks')], null=True, verbose_name='times a week'),
        ),
    ]
