# Generated by Django 3.1.2 on 2020-10-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_people', '0006_auto_20201010_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitperson',
            name='contact',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='kitperson',
            name='priority',
            field=models.CharField(choices=[('T', 'Top'), ('H', 'High'), ('O', 'Other')], max_length=2, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='regularity',
            name='reminder',
            field=models.TimeField(blank=True, null=True, verbose_name='reminder time'),
        ),
    ]
