# Generated by Django 3.1.2 on 2020-10-24 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kit_people', '0008_auto_20201013_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitperson',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kit_people.role', verbose_name='role'),
        ),
    ]
