# Generated by Django 3.1.2 on 2020-11-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    def change_priority_to_one(apps, schema_editor):
        Priority = apps.get_model('kit_people', 'KitPerson')

        for obj in Priority.objects.all():
            obj.priority = 1
            obj.save()

    dependencies = [
        ('kit_people', '0010_auto_20201028_1914'),
    ]

    operations = [
        migrations.RunPython(change_priority_to_one),
        migrations.AlterField(
            model_name='kitperson',
            name='priority',
            field=models.IntegerField(verbose_name='priority'),
        ),
    ]
