# Generated by Django 3.1.2 on 2020-11-11 16:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):
    def clear_regularities_with_null_kit_person(apps, schema_editor):
        Regularity = apps.get_model('kit_people', 'Regularity')

        for obj in Regularity.objects.all():
            if obj.kit_person is None:
                obj.delete()

    dependencies = [
        ('kit_people', '0012_auto_20201111_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularity',
            name='time_of_month',
            field=models.CharField(blank=True,
                                   choices=[('BE', 'Beginning'), ('MI', 'Middle'), ('EN', 'End'), ('AN', 'Any time')],
                                   max_length=2, null=True, verbose_name='time of month'),
        ),
        migrations.AlterField(
            model_name='regularity',
            name='week_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True,
                                                              choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'),
                                                                       (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'),
                                                                       (6, 'Sunday')], max_length=13, null=True,
                                                              verbose_name='week days'),
        ),
        migrations.RunPython(clear_regularities_with_null_kit_person),
    ]
