# Generated by Django 3.1.2 on 2020-11-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_people', '0013_auto_20201111_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitperson',
            name='chatApp',
            field=models.IntegerField(default=0, verbose_name='chat app'),
        ),
    ]
