# Generated by Django 3.1.2 on 2020-10-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.CharField(max_length=256, unique=True, verbose_name='FCM token'),
        ),
    ]
