# Generated by Django 3.1.2 on 2020-12-02 21:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0002_lessonlikes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonLikes',
            new_name='LessonLike',
        ),
    ]
