# Generated by Django 3.1 on 2020-09-27 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=16, unique=True, verbose_name='day')),
            ],
        ),
        migrations.CreateModel(
            name='Periodicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DayPeriodicity',
            fields=[
                ('periodicity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='habit.periodicity')),
                ('times', models.IntegerField()),
                ('days', models.IntegerField()),
            ],
            bases=('habit.periodicity',),
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
                ('description', models.CharField(max_length=4096, verbose_name='description')),
                ('periodicity', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='habit.periodicity', verbose_name='periodicity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('COUNT', 'Count'), ('SEC', 'Seconds'), ('MET', 'Meters'), ('PAGES', 'Pages')], max_length=16, verbose_name='unit')),
                ('value', models.IntegerField()),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='habit.habit', verbose_name='habit')),
            ],
        ),
        migrations.CreateModel(
            name='WeekPeriodicity',
            fields=[
                ('periodicity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='habit.periodicity')),
                ('days_of_week', models.ManyToManyField(related_name='week_periodicity', to='habit.DayOfWeek', verbose_name='week periodicity')),
            ],
            bases=('habit.periodicity',),
        ),
    ]
