# Generated by Django 3.1 on 2020-10-19 20:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='habit',
            name='start_day',
            field=models.DateField(default=datetime.date(2020, 10, 19)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('COUNT', 'Count'), ('SEC', 'Seconds'), ('MET', 'Meters'), ('PAGES', 'Pages')], max_length=16, verbose_name='unit')),
                ('completed', models.IntegerField()),
                ('out_of', models.IntegerField()),
                ('date', models.DateField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='habit.habit', verbose_name='habit')),
            ],
        ),
    ]
