# Generated by Django 3.1 on 2020-10-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_note_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_good',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
